### ISSUE TITLE
Timestamps on changes.json

### ISSUE THREAD

**Issue by Gaelan** [AgoraNomic/Cartographor#2]
I'm hoping to consume your event log to help with Treasuror automation (namely resource generation in facilities)—would you mind adding timestamps to your changes.json so that I can tell what state the facilities are in at the end of a week? (Also, having timestamps is probably a good idea anyway for reporting history.) Thanks!

**Comment by CodeTriangle** [comment]
I'm working on a much simpler system to implement changes right now that
will track all of that. I'll be happy to share with you how to use the
system, just be patient.

**Comment by CodeTriangle** [comment]
I just pushed my changes. It's not wired into generate.py yet, but data/changes.fr does work. fractal.py interprets it so you can get all the changes back into json. If you're still confused, I can help you out.
